### ISSUE TITLE
check-circle

### ISSUE THREAD

**Issue by windchime11** [Templarian/MaterialDesignLight#1]
Looks like this but in material design light style. 
![ic_tracker](https://cloud.githubusercontent.com/assets/1188350/26598288/ddfedadc-4542-11e7-8058-b127e8fae229.png)
![ic_dollar](https://cloud.githubusercontent.com/assets/1188350/26598319/f40b4e96-4542-11e7-8e17-6d62ab47a266.png)

Also one for check within a circle?

**Comment by windchime11** [comment]
please also make a share icon. Sharing content

**Comment by PeterShaggyNoble** [comment]
Thanks for getting the ball rolling in this new repo, @windchime11.

`truck` has been added and will be available in the next release.

As it's a new icon, can you open an issue in [our main repo](https://github.com/Templarian/MaterialDesign) for `price-lock`? Note, though, that we are no longer adding currency-specific icons so we'll need to figure out another way to represent this.

I've created a new issue (#7) for the `share` icon. To help us better track requests, please limit issues to a single icon (or related group of icons).

That just leaves `check-circle` outstanding from this issue. Renaming accordingly.

[![truck](https://user-images.githubusercontent.com/15157491/49795681-849eec80-fd32-11e8-9338-14da123b35bb.png)](http://dev.materialdesignicons.com/icon/truck/light)

**Comment by mririgoyen** [comment]
![image](https://user-images.githubusercontent.com/1015040/89142341-24ffe100-d515-11ea-89a4-d3adaf2bc129.png)
[check-circle.svg.zip](https://github.com/Templarian/MaterialDesignLight/files/5013636/check-circle.svg.zip)
