### ISSUE TITLE
webfont light icon

### ISSUE THREAD

**Issue by faybak** [Templarian/MaterialDesignLight#12]
hello. I looking for webfont light icons. But when I download the repo to use on Kivy, it's appear to not be light. how can I get it please?
![Capture d’écran 2020-08-14 à 14 38 14](https://user-images.githubusercontent.com/49174660/90250073-cbb07f80-de3b-11ea-865d-d19fed9145a7.png)

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesignLight-Webfont

https://cdn.materialdesignicons.com/light/0.2.63/

**Comment by faybak** [comment]
its what I used and when I want to see the icon I obtain that icon I put on the pics

**Comment by Templarian** [comment]
Can you double check it's actually the `Light` webfont. Do you see the light icons the CDN fine?

**Comment by faybak** [comment]
I used this url to download webfont icons: https://github.com/Templarian/MaterialDesignLight-Webfont

and I have the same result. It's not light icon. please help
