### ISSUE TITLE
loading

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesignLight#3]
Need the `loading` icon translated. It's messing up the preview.html

**Comment by Templarian** [comment]
Added. I don't have preview code setup, so can't do the fancy previews just yet.

**Comment by PeterShaggyNoble** [comment]
[![loading](https://user-images.githubusercontent.com/15157491/50634974-44edae00-0f48-11e9-93d2-3a064759d263.png)](http://dev.materialdesignicons.com/icon/loading/light)
