### ISSUE TITLE
Gender icons

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesignLight#5]
![image](https://user-images.githubusercontent.com/15905797/49701370-7ee6c100-fbe3-11e8-9a0a-41fbd821f998.png)![image](https://user-images.githubusercontent.com/15905797/49701377-9756db80-fbe3-11e8-997e-daf252e504d6.png)![image](https://user-images.githubusercontent.com/15905797/49701380-a473ca80-fbe3-11e8-8173-8e17007355bc.png)![image](https://user-images.githubusercontent.com/15905797/49701384-af2e5f80-fbe3-11e8-8351-3c8376c97b18.png)

[gender.zip](https://github.com/Templarian/MaterialDesignLight/files/2660897/gender.zip)

**Comment by mririgoyen** [comment]
Added.
