### ISSUE TITLE
Share

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesignLight#7]
Separating out the request for `share` (and `share-variant`?) from #1.

**Comment by r3volution11** [comment]
Here are both `share` and `share-variant` icons. Hope these work! 😎

[share+share-variant.zip](https://github.com/Templarian/MaterialDesignLight/files/2670031/share%2Bshare-variant.zip)

**Comment by PeterShaggyNoble** [comment]
Previews of @r3volution11's contributions:

![share](https://user-images.githubusercontent.com/15157491/50009111-0e0e2300-ffae-11e8-8ca4-d07c3c15ede4.png) ![share-variant](https://user-images.githubusercontent.com/15157491/50009163-339b2c80-ffae-11e8-9e85-7d20e929b9a4.png)

**Comment by mririgoyen** [comment]
Just noticed that those contributions are on a 24x24 grid, so they'll need to be adjusted for the 23x23 grid we use for light.

**Comment by mririgoyen** [comment]
Both added.
