### ISSUE TITLE
Equalizer

### ISSUE THREAD

**Issue by romaluca** [Templarian/MaterialDesignLight#9]
Is possible to have the light icon of equalizer?

https://materialdesignicons.com/icon/equalizer-outline

Thanks!

**Comment by mririgoyen** [comment]
![image](https://user-images.githubusercontent.com/1015040/89141982-27ae0680-d514-11ea-9073-02eddb8946e2.png)
[equalizer.svg.zip](https://github.com/Templarian/MaterialDesignLight/files/5013626/equalizer.svg.zip)

**Comment by mririgoyen** [comment]
Please don't close issues. We'll close once the icon has been added. 😀

**Comment by mririgoyen** [comment]
Added.
